### GET ALL ITEMS

GET http://localhost:5000/items HTTP/1.1


### GET SINGLE ITEM

GET http://localhost:5000/items/1 HTTP/1.1

### add ITEM

POST http://localhost:5000/items HTTP/1.1
Content-Type: application/json

{
    "name": "new item"
}

### Delete ITEM

delete http://localhost:5000/items/1 HTTP/1.1

### Update ITEM

PUT http://localhost:5000/items/2 HTTP/1.1
Content-Type: application/json

{
    "name": "updated item"
}